//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Account.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enterprise
    {
        public int Id { get; set; }
        public string EnterpriseName { get; set; }
        public string EnterpriseAddress { get; set; }
        public string ContactUser { get; set; }
        public string ContactTel { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
