//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Account.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string UserAccount { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string Telephone { get; set; }
        public int EnterpriseId { get; set; }
        public int DepId { get; set; }
        public int PostId { get; set; }
        public string Remarks { get; set; }
        public int Status { get; set; }
        public int ManageLevel { get; set; }
        public string ImgUrl { get; set; }
    }
}
